### ISSUE TITLE
JOSE review: Licensing 

### ISSUE THREAD

**Issue by lheagy** [darribas/gds18#1]
This is related to: openjournals/jose-reviews#42

The license specified in the [LICENSE](https://github.com/darribas/gds18/blob/master/LICENSE) file (CC-BY-NC-SA) is not the same as that listed in the [README](https://github.com/darribas/gds18/blob/master/README.md#license) (CC-BY), so they should be updated to be consistent. 

With respect to license choice, I would encourage you to consider not using the `NC` portion of the Creative Commons License, as it is fairly restrictive on how others can use the content you developed (see the creative commons explanation on "Free Cultural Work": https://creativecommons.org/share-your-work/public-domain/freeworks)

**Comment by darribas** [comment]
Thank you very much for catching this and suggesting a solution! I've decided to go for CC-BY-SA.

In the process of fixing this, I've also realised licensing was very inconsistent across the content. Hopefully e5b54178a3d9feed6d9059f56dff0c0e66265c88, eda7b3e80dd23f7cbd26b29dd511d4c7b9e27349 and 3b5f9569270edb026cf68b85732f68e639271e82 address this.

[Closing but feel free to re-open if anything is unclear or missing]
