### ISSUE TITLE
Include `dill` and `rtree` in conda file?

### ISSUE THREAD

**Issue by jsta** [darribas/gds18#2]
This is related to: [openjournals/jose-reviews#42](https://github.com/openjournals/jose-reviews/issues/42)

I get a warning in several notebooks about not having `dill` installed. Even if not needed it might be good to include so learners don't think there is a problem with their installation. 

Lab 3 mentions using `rtree` for spatial joins.

**Comment by darribas** [comment]
Thanks very much for the comment!

* On `dill`, can you provide a specific example where that happens? I have not run into that, from memory. I'm happy to dig further.
* On `rtree`, it actually now installs automatically when `geopandas` is installed via conda:

```shell
(gds) dh073194:gds18 dani$ conda list | grep rtree
rtree                     0.8.3                 py36_1000    conda-forge
(gds) dh073194:gds18 dani$
```
Also, it is a library the end-user does not need to interact with. For those reasons, I've removed the mention in Lab 3 (1e358ff43bf3590baa3d593d4e8c94553c9a8776).

**Comment by jsta** [comment]
Hmm, I can no longer reproduce the `dill` warnings. Looks good on `rtree` :+1:

**Comment by darribas** [comment]
Fantastic! Closing this one, but feel free to re-open if needed.
