### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by lheagy** [darribas/gds18#6]
I am following the Linux / OS instructions. This is minor, but for activating a conda environment, the preferred way is now `conda activate` rather than `source activate` (as of [conda 4.4.0](https://github.com/conda/conda/blob/master/CHANGELOG.md#new-feature-highlights-2)). Other than that everything looks good :) 

(part of the JOSE review in openjournals/jose-reviews#42)

**Comment by darribas** [comment]
Great catch! Addressed in #17a064450a9793c778640c5a04e3044fd714e612

[Closing for now but feel free to re-open if need be]
